# Generated by Django 4.1.5 on 2023-02-06 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_type_userprofile_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(help_text="user's date of birth"),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='father_name',
            field=models.CharField(blank=True, help_text="user's father name", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mother_name',
            field=models.CharField(blank=True, help_text="user's mother name ", max_length=100, null=True),
        ),
    ]
