# Generated by Django 4.1.5 on 2023-02-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_code', models.CharField(help_text='Course code', max_length=10)),
                ('course_name', models.CharField(help_text='course name', max_length=100)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
    ]
